server.port=8080

# CONNECTING LIVE TO AIVEN CLOUD DATA TIER USING ENVIRONMENT VARIABLES
spring.datasource.url=jdbc:mysql://mysql-303ecdf-eashenraj256-7a60.h.aivencloud.com:22323/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=${DB_USERNAME:avnadmin}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Let Hibernate automatically build your 6 required tables on the cloud database instance
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true